config/routes.rb
Rails.application.routes.draw do
  get 'collaborators/index'

  resources :wikis do
    resources :collaborators, only: [:index, :create, :destroy]
  end

  devise_for :users
  get 'welcome/index'

  get 'welcome/about'

  root to: 'welcome#index'

  resources :charges, only: [:new, :create]
  get 'charges/downgrade'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :collaborators

  has_many :wikis


  after_initialize :init

  enum role: [:standard, :premium, :admin]

  def init
    role = :standard
  end



end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
    new_record?
  end

  belongs_to :user

  has_many :collaborators
  has_many :users, through: :collaborators, dependent: :destroy

  scope :visible_to, -> (user) { user ? all : where(public: true) }

  def collaborator_for(user)
    collaborators.where(user: user).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protect_from_forgery with: :exception

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

def create

  # Creates a Stripe Customer object, for associating
  # with the charge
  customer = Stripe::Customer.create(
    email: current_user.email,
    card: params[:stripeToken]
  )

  # Where the real magic happens
  charge = Stripe::Charge.create(
    customer: customer.id, # Note -- this is NOT the user_id in your app
    amount: 10_00,
    description: "BigMoney Membership - #{current_user.email}",
    currency: 'usd'
  )

  current_user.premium!

  flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
  redirect_to wikis_path # or wherever

# Stripe will send back CardErrors, with friendly messages
# when something goes wrong.
# This `rescue block` catches and displays those errors.
rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end

def new
  @stripe_btn_data = {
    key: "#{ Rails.configuration.stripe[:publishable_key] }",
    description: "BigMoney Membership - #{current_user.email}",
    amount: 10_00
  }
end

def downgrade
  current_user.standard!
  current_user.wikis.update_all(private: false)
  flash["notice"] = "Your account has been downgraded"
  redirect_to edit_user_registration_path
end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_wiki

  def index
    @users = User.all
  end

  def create
    @collaborator = @wiki.collaborators.new(user_id: params[:user_id])
    if @collaborator.save
      flash[:notice] = "your collaborator was added"
    else
      flash[:error] = "No bueno!"
    end
    redirect_to wiki_collaborators_path(@wiki)
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])
    if @collaborator.destroy
      flash[:notice] = "Your collaborator was removed"
    else
      flash[:error] = "No bueno!"
    end
    redirect_to wiki_collaborators_path(@wiki)
  end

  private

  def set_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :set_wiki, only: [:show, :edit, :update, :destroy]

  # GET /wikis
  def index
    @wikis = policy_scope(Wiki)
  end

  # GET /wikis/1
  def show
    unless !@wiki.private? || current_user
      flash[:error] = "You must be signed in to view private topics."
      redirect_to new_session_path
    end
  end

  # GET /wikis/new
  def new
    @wiki = Wiki.new
  end

  # GET /wikis/1/edit
  def edit
    authorize @wiki
  end

  # POST /wikis
  def create
    @wiki = current_user.wikis.new(wiki_params)
    authorize @wiki

    if @wiki.save
      redirect_to @wiki, notice: 'Wiki was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /wikis/1
  def update
    authorize @wiki
    if @wiki.update(wiki_params)
      redirect_to @wiki, notice: 'Wiki was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /wikis/1
  def destroy
    @wiki.destroy
    redirect_to wikis_url, notice: 'Wiki was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wiki
      @wiki = Wiki.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def wiki_params
      params.require(:wiki).permit(:title, :body, :private)
    end



end

app/helpers/application_helper.rb
require 'redcarpet'

module ApplicationHelper
  def markdown(text)
    if text
      markdown = Redcarpet::Markdown.new(
        Redcarpet::Render::HTML.new
      )
      markdown.render(text).html_safe
    end
  end
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborators/index.html.erb
<h1>Collaborators for <%= @wiki.title %></h1>
<table class="table">
  <th>User</th>
  <th></th>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td>
        <% if @wiki.users.include? user %>
          <%= link_to 'Remove as Collaborator', wiki_collaborator_path(@wiki, @wiki.collaborator_for(user)), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% else %>
          <%= link_to 'Add as Collaborator', wiki_collaborators_path(@wiki, user_id: user.id), method: :post %>
        <% end %>
      </td>
    </tr>
  <% end %>



</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
     <li><%= link_to "Home", welcome_index_path %></li>
     <li><%= link_to "About", welcome_about_path %></li>
     <li><%= link_to "Wikis", wikis_path %></li>
     <div class="pull-right user-info">
         <% if current_user %>
         <strong><%= current_user.email %></strong>
         <%= link_to 'Edit profile', edit_user_registration_path %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete %></p>
       <% else %>
         <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
         <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
       <% end %>
       </div>

  </ul>

  <div class="flash">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
  </div>

<%= yield %>
</div>

</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/about.html.erb
<h1>About Blocipedia</h1>
<p>Created by: Me</p>

app/views/welcome/index.html.erb
<h1>Welcome to Blocipedia</h1>
<p>This is the home page for Bloccit.</p>

app/views/wikis/_form.html.erb
<%= form_for(@wiki) do |f| %>

  <% if @wiki.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wiki.errors.count, "error") %> prohibited this wiki from being saved:</h2>

      <ul>
      <% @wiki.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>

  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Editing Wiki</h1>

<%= render 'form' %>

<% if current_user.premium? && @wiki.private? || current_user.admin?  %>
  <%= link_to 'Add Collaborator', wiki_collaborators_path(@wiki) %> |
<% end %>

<%= link_to 'Show', @wiki %> |
<%= link_to 'Back', wikis_path %>

app/views/wikis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wikis</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Private</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wikis.each do |wiki| %>
      <tr>
        <td><%= wiki.title %></td>
        <td><%= wiki.private  %></td>
        <td><%= wiki.user.email %></td>
        <td><%= link_to 'View', wiki %></td>
        <td><%= link_to 'Edit', edit_wiki_path(wiki) %></td>
        <td>
          <% if current_user.admin? %>
          <%= link_to 'Delete', wiki, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wiki', new_wiki_path %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<%= render 'form' %>



<%= link_to 'Back', wikis_path %>

app/views/wikis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @wiki.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= markdown(@wiki.body) %>
</p>

<p>
  <strong>Private:</strong>
  <%= @wiki.private %>
</p>

<p>
  <strong>User:</strong>
  <%= @wiki.user.email %>
</p>

<% if policy(@wiki).update? %>
  <%= link_to 'Edit', edit_wiki_path(@wiki) %>
<% end %> |
<%= link_to 'Back', wikis_path %>